name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f45f2035dfd12b1e5eaab0313031a3bb6965101814aae86628e5bc8b0df3250e"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
