name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27336c8b59670804678e6d3f9ef8cd82e9f6c17ed062f25fbae3527c3166e51b"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
