name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89cbafa91cfb08a2489f2ca5038ebc91af7c29419844af16fe5e35c1582fb126"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
