name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19fa3e81132e6ab160f6315ba95bf11bd253c809fc6f360445468ba5450c4c68"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
