name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e734e2ae3f61383308d1e69841c5f021e51ca8bf169df3281ba33dc8e793deb"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
