name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd83b5cef78dd71233fffd32c78e90e05c557e4984ee3082e759fc58dfc84b3d"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
