name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "143edb18ecbc19aa55ee9cafc38bba9dfd5b2724bf91a751d08115d709f6909a"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
