name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c6c3498e9993a1a066622945569cbecdb66ec6d17fa24d9e7664167a3d4150f"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
