name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a462e10038868576495ff6ce2ab23d8e5d75229802ec476c06f6bc64cdf40d3"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
