name = "Farwater Create"
version = "Season 8 v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d780130a085bc3dff83a2aa5564e762fd18f9b79335d439b85619d13b7909c7"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
